spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/bank
    username: root
    password: root

    hikari:
      maximumPoolSize: 20
      poolName: HikariCP

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
