# 작업명
name: CD NCP
on:
  push:
    branches:
      - 'develop'
      - 'main'
jobs:
  CI:
    runs-on: ubuntu-latest
    # 작업 실행 단계
    steps:
      # 체크아웃 및 JDK 세팅
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # Gradle 권한 부여
      - name: Grant Execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      # test하지 않고 빌드를 진행
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
#      # local환경으로 테세트 진행
#      - name: Test with Gradle
#        run: SPRING_PROFILES_ACTIVE=[local] ./gradlew clean test
#        shell: bash